source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, ‘8.0’
inhibit_all_warnings!

xcodeproj 'SideBarMenuController'

target 'SideBarMenuController_Example' do
  pod 'SideBarMenuController', :path => '../'
end